name: CI-doxygen-publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  doxygen-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: iotivity-lite

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.IOTIVITY_LITE_SSH_KEY }}

      - name: doxygen_build_documentation
        run: |
          sudo apt-get update -y
          sudo apt-get install doxygen
          doxygen --version
          cd ${{ github.workspace }}/iotivity-lite/tools
          ./build_doc.sh

      - name: doxygen_copy-docs
        run: |
          cd ~/work
          git clone git@github.com:iotivity/iotivity-lite-doxygen.git
          cd iotivity-lite-doxygen
          rm -rf docs
          cp -r ${{ github.workspace }}/iotivity-lite/tools/html .
          #Rename to "docs"
          mv html docs

      - name: doxygen_push-changes
        run: |
          cd ~/work/iotivity-lite-doxygen
          git config --global user.name 'IoTivity Bot'
          git config --global user.email 'github@iotivity.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/iotivity/iotivity-lite"
          git push
